Feature friends
WhuApp/backend pull request #2
Opened 2023-08-13 22:44 UTC by gerbernoah

2023-08-13 23:04 UTC, HurricanKai requested changes
This is a big one - got some fundamentalish changes I'd recommend

In addition I think it might make sense to just define a type at the top that takes the authCtx + friendId everywhere, wraps it in a nice stateful object, and we can then add helper functions to contain a lot of the duplicated logic?
ie `type FriendPair = { me: User, other: User }; type User = { id: string };` + associated functions to do things like get the in/out, friend list.
(I'd recommend first validating the ID is actually present (for `other`) before construction the object)
Would only do this transformation after what I've mentioned in review comments though!

2023-08-13 23:04 UTC, HurricanKai commented on src/services/friends.ts
> +				}
I think these are short enough to keep in line - not sure. Maybe still outline just to make it consistent?

2023-08-13 23:04 UTC, HurricanKai commented on src/services/friends.ts
> +};
tbd: review these - not doing that right now given I recommend to reformat these and it kinda seems like a lot of logic will go away?

2023-08-13 23:09 UTC, gerbernoah commented on src/services/friends.ts
> +					if (!(await userExists(body.friendId, env))) return new Response('Other user not found', { status: 400 });
@7rebux insisted on not using 404 since in his opinion this states "endpoint not found"

2023-08-13 23:20 UTC, gerbernoah commented on src/services/friends.ts
> +					if (!ownInRequests.includes(body.friendId)) return new Response(`Request expired`, { status: 400 });
I am completely with you. This interleaving just happens to be more efficient, since we can return the function at the first failing condition without requesting unnecessary KV data

2023-08-13 23:27 UTC, 7rebux requested changes
Add brackets to all if statements so the code is more readable overall and prettier will wrap the if body to a new line.

2023-08-13 23:27 UTC, 7rebux commented on src/auth.ts
> +}
Stay consistent with camel case naming. Also are these console logs helpful or just for debugging reasons?

2023-08-13 23:27 UTC, 7rebux commented on src/auth.ts
> +}
```suggestion
export async function authenticateUser(headers: Headers): Promise<AuthObject> {
	const auth = headers.get('Authorization');
	
	if (auth === null) {
		throw new Error('Missing authorization header');
	}

	const [scheme, token] = auth.split(' ');
	
	if (scheme !== 'Bearer') {
		throw new Error('Unknown Scheme: ' + scheme);
	}

	const tokenObject = await verifyToken(token);

	return { userId: (tokenObject as any).sub };
}
```

2023-08-13 23:27 UTC, 7rebux commented on src/services/friends.ts
> +					const authCtx = await authenticateUser(request.headers);
Just call this thing `authContext`

2023-08-13 23:27 UTC, 7rebux commented on src/services/friends.ts
> +					const body: { friendId: string } = await request.json();
Do not inline types

2023-08-13 23:27 UTC, 7rebux commented on src/services/friends.ts
> +					if (body.friendId === authCtx.userId) return new Response('You cannot send yourself a friendrequest', { status: 400 });
```suggestion
					if (body.friendId === authCtx.userId) return new Response('Can not request yourself', { status: 400 });
```

2023-08-13 23:27 UTC, 7rebux commented on src/services/friends.ts
> +					if (!ownInRequests.includes(body.friendId)) return new Response(`Request already expired`, { status: 400 });
```suggestion
					if (!ownInRequests.includes(body.friendId)) return new Response(`Request expired`, { status: 400 });
```

2023-08-13 23:27 UTC, 7rebux commented on src/services/friends.ts
> +	console.log(ownOutRequests);
Is this log necessary?

2023-08-13 23:27 UTC, 7rebux commented on src/services/friends.ts
> +	ownInRequests ??= (await env.REQUESTS_IN_KV.get(userId, 'json')) ?? [];
Really hard to read. Try not to use two declarations in the same line. Maybe replace the `??=` with an simple if statement just for readability

2023-08-13 23:27 UTC, 7rebux commented on src/services/friends.ts
> +	ownInRequests.filter((x) => x != friendId);
```suggestion
	ownInRequests = ownInRequests.filter((x) => x != friendId);
```

2023-08-13 23:27 UTC, 7rebux commented on src/utils.ts
> +	myHeaders.append('Authorization', body.token_type + ' ' + body.access_token);
```suggestion
	myHeaders.append('Authorization', `${body.token_type} ${body.access_token}`);
```

2023-08-13 23:27 UTC, 7rebux commented on src/utils.ts
> +			throw new Error('Something went wrong. Auth0 statuscode: ' + (await auth0Response.text()));
Cleanup this error message

2023-08-14 14:08 UTC, HurricanKai commented on src/services/friends.ts
> +					if (!(await userExists(body.friendId, env))) return new Response('Other user not found', { status: 400 });
Sure - but the suggestion isn't about changing this to 404, but instead have the error message reflect that.

2023-08-14 15:05 UTC, gerbernoah commented on src/services/friends.ts
> +};
What do you mean with "seems like a lot of logic will go away" this doesnt sound like a positive goal one wants to archieve

2023-08-14 15:48 UTC, gerbernoah commented on src/services/friends.ts
> +	ownInRequests ??= (await env.REQUESTS_IN_KV.get(userId, 'json')) ?? [];
I think `??=` is just fine. There is no neat alternative.

2023-08-14 16:25 UTC, HurricanKai requested changes

2023-08-14 16:25 UTC, HurricanKai commented on src/services/friends.ts
> +	await env.REQUESTS_OUT_KV.put(userId, JSON.stringify(ownOutRequests));
Either group them, or don't. Grouping the first two statements and then not the other two is super confusing

2023-08-14 16:25 UTC, HurricanKai commented on src/services/friends.ts
> +		return requestAccept(userId, friendId, env, friendInRequests, ownOutRequests);
Not sure if this makes sense - why reuse this? We have bunch of logic now that directly reverses the logic above?

2023-08-14 16:25 UTC, HurricanKai commented on src/services/friends.ts
> +		return requestAccept(userId, friendId, env, friendInRequests, ownOutRequests);
So we pass friendInRequests & ownOutRequests but not friendOutRequests - seems inconsistent?

2023-08-14 16:25 UTC, HurricanKai commented on src/services/friends.ts
> +		return new Response(`Request expired`, { status: 400 });
"expired" implies some kind of timing - reword

2023-08-15 04:16 UTC, 7rebux requested changes

2023-08-15 04:16 UTC, 7rebux commented on src/services/friends.ts
Still a lot of reused logic as @HurricanKai already mentioned. Please look into that @gerbernoah ♻️!
Also we are passing `env` to literally everything is there no easier way of doing this?

2023-08-15 04:19 UTC, 7rebux commented on src/services/friends.ts
> +					if (!ownInRequests.includes(body.friendId)) return new Response(`Request expired`, { status: 400 });
I agree with @gerbernoah there

2023-08-15 04:22 UTC, 7rebux commented on src/services/friends.ts
> +		return requestAccept(userId, friendId, env, friendInRequests, ownOutRequests);
I also agree with this one - good readability tho

2023-08-16 05:03 UTC, HurricanKai commented
Closing in favor of #3 #4 #5

2023-08-16 05:03 UTC, closed without merging