convert if to switch case
WhuApp/backend pull request #22
Opened 2023-08-19 22:33 UTC by gerbernoah

2023-08-20 17:25 UTC, 7rebux reviewed
This does not really simplify the logic

2023-08-20 19:06 UTC, gerbernoah commented
I believe it really does simplify the process of adding new endpoints

2023-08-21 09:23 UTC, 7rebux requested changes
Still some work to do there. Please append the same things that I pointed out in `friends_v1` to `users_v1` and `locations_v1`. Gonna do another review after this stuff is adjusted!

2023-08-21 09:23 UTC, 7rebux commented on src/services/friends_v1.ts
> +export default Object.assign(
Would rather create a constant like FriendsV1 and export that

2023-08-21 09:23 UTC, 7rebux commented on src/services/friends_v1.ts
> +    fetch: async (request: Request, env: Env, subpath: string): Promise<Response> => {
Return type should already be infered from the type

2023-08-21 09:23 UTC, 7rebux commented on src/worker.ts
> +      const services: Service[] = [friendsService, usersService, locationsService];
Do it like this: https://stackoverflow.com/questions/61436556/es6-typescript-import-all-exported-constants-as-an-array.
So new services just need to be exported in `services/index.ts` to be registered.

2023-08-21 09:23 UTC, 7rebux commented on src/worker.ts
> +      );
No need to extract version and service name separately

2023-08-21 09:23 UTC, 7rebux commented on src/worker.ts
> +      //maybe execute all found services. Atm just execute the first valid one found
What? This wont work anyways because it just returns an response after the first one already. Also this makes no sense why would we want to do that?

2023-08-21 09:23 UTC, 7rebux commented on src/worker.ts
> +      if (activeServices.length == 1)
Just search for the first one and execute it with `service?.fetch(...)` then throw error afterwards in case no service was found

2023-08-21 09:23 UTC, 7rebux commented on src/worker.ts
>        throw new Error();
Can this error please be specified, something like "Service not found"

2023-08-21 09:23 UTC, 7rebux commented on src/worker.ts
> +    } catch (error: any) {
I suggest using `unknown` instead of `any` in catch scenarios.

2023-08-25 11:18 UTC, 7rebux approved these changes

2023-08-25 11:18 UTC, merged